<?php View::content() ?>
<table class="table display nowrap">
	<thead>
		<th>Fecha</th>
		<th>Plantilla</th>
		<!-- <th>Usuario</th> -->
		<th>Nombre del Paciente</th>
		<th>Historia Clinica</th>
		<th>Fecha de operacion</th>
		<th>Cirujano Principal</th>
		<th>Equipo</th>
		<th>PDF</th>
	</thead>
	<?php foreach ($intervenciones as $key => $value): ?>
		<?php $info = unserialize($value->formulario) ?>
		<tr>
			<td><?php echo $value->creado ?></td>
			<td><?php echo $value->plantilla_nombre ?></td>
			<td><?php echo $info['nombre'] ?></td>
			<td><?php echo $info['hc'] ?></td>
			<td><?php echo $info['fecha'] ?></td>
			<td><?php echo $info['cirujano1'] ?></td>
			<?php $archivo = Util::verNombreArchivoPdf($value->url_pdf) ?>
			<?php $equipos = Load::model("usuario_equipo")->find("conditions: usuario_id = '".$value->usuario_id."'") ?>
			<?php $nombre_equipos=array() ?>
			<?php if ($equipos): ?>
				<?php foreach ($equipos as $key2 => $value2): ?>
					<?php $equipo = Load::model("equipo")->find($value2->equipo_id) ?>
					<?php $nombre_equipos[]=$equipo->nombres_abreviado ?>
				<?php endforeach ?>
			<?php endif ?>
			<td><?php echo implode(", ",$nombre_equipos) ?></td>
			<td><?php echo Html::link("archivos/get_/".$archivo,"Ver PDf","target='_blank'") ?></td>
		</tr>
	<?php endforeach ?>
</table>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.2/css/buttons.dataTables.min.css">
<script type="text/javascript" src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.1.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.1.2/js/buttons.flash.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.1.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.1.2/js/buttons.print.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
    $('.table').DataTable( 
    	<?php if (Auth::is_valid() and (Auth::get('rol') == 1 or Auth::get('rol') == 2 or Auth::get('rol') == 3)): ?>

		    {
		        dom: 'Bfrtip',
		        buttons: [
		            'copy', 'csv', 'excel', 'pdf', 'print'
		        ]
		    } 
    	<?php endif; ?>
    );
});
</script>